# Generated by Django 4.2.10 on 2024-03-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_type_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
