# Generated by Django 4.2.10 on 2024-03-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_card_type_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shareable_card_limit',
        ),
    ]
