# Generated by Django 4.2.10 on 2024-03-05 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cardpopularity_remove_sociallink_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='card_backgrounds/')),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='carddesign',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='design',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carddesign'),
        ),
        migrations.AddField(
            model_name='card',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='brand_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='font_family',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='front_product_image',
            field=models.ImageField(blank=True, upload_to='card_designs/'),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.datetime(2024, 3, 5, 7, 53, 1, 259069, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carddesign',
            name='logo',
            field=models.ImageField(blank=True, upload_to='card_designs/'),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='motto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='text_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='back_background_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_designs', to='core.backgroundimagetemplate'),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='front_background_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_designs', to='core.backgroundimagetemplate'),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.layout'),
        ),
    ]
