# Generated by Django 4.2.10 on 2024-03-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backgroundimagetemplate_layout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
    ]
