# Generated by Django 4.2.10 on 2024-03-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_bio_user_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='biography',
        ),
    ]
