# Generated by Django 4.2.10 on 2024-03-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_bio_user_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
    ]
