# Generated by Django 4.2.10 on 2024-03-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_biography_remove_user_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='design',
        ),
        migrations.RemoveField(
            model_name='card',
            name='other_professions',
        ),
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='card',
            name='primary_profession',
        ),
        migrations.RemoveField(
            model_name='carddesign',
            name='back_background_template',
        ),
        migrations.RemoveField(
            model_name='carddesign',
            name='front_background_template',
        ),
        migrations.RemoveField(
            model_name='carddesign',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='cardpopularity',
            name='card',
        ),
        migrations.RemoveField(
            model_name='cardshare',
            name='card',
        ),
        migrations.RemoveField(
            model_name='sharing',
            name='card',
        ),
        migrations.RemoveField(
            model_name='sharing',
            name='shared_from',
        ),
        migrations.RemoveField(
            model_name='sharing',
            name='shared_to',
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
        migrations.DeleteModel(
            name='BackgroundImageTemplate',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardDesign',
        ),
        migrations.DeleteModel(
            name='CardPopularity',
        ),
        migrations.DeleteModel(
            name='CardShare',
        ),
        migrations.DeleteModel(
            name='Layout',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='Sharing',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='SocialPlatform',
        ),
    ]
