# Generated by Django 4.2.10 on 2024-03-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
