# Generated by Django 4.2.10 on 2024-03-11 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_profession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='card_backgrounds/')),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sharable', models.BooleanField(default=True)),
                ('shared_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_media_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='CardPopularity',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='card_manager.card')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('saved_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_manager.card')),
                ('shared_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_from', to=settings.AUTH_USER_MODEL)),
                ('shared_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_through', models.CharField(choices=[('email', 'Email'), ('qr_code', 'QR Code'), ('other', 'Other')], default='other', max_length=50)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_manager.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, upload_to='card_designs/')),
                ('brand_color', models.CharField(blank=True, max_length=7)),
                ('front_product_image', models.ImageField(blank=True, upload_to='card_designs/')),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('text_color', models.CharField(blank=True, max_length=7)),
                ('font_family', models.CharField(blank=True, max_length=255)),
                ('back_background_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_designs', to='card_manager.backgroundimagetemplate')),
                ('front_background_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_designs', to='card_manager.backgroundimagetemplate')),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='card_manager.layout')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='design',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card_manager.carddesign'),
        ),
        migrations.AddField(
            model_name='card',
            name='other_professions',
            field=models.ManyToManyField(blank=True, related_name='other_professions', to='core.profession'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='primary_profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_professions', to='core.profession'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_manager.socialplatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
