# Generated by Django 4.2.10 on 2024-03-11 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='share_limit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='card',
            name='third_party_share_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='card',
            name='third_party_shared_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardshare',
            name='shared_with',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
