# Generated by Django 4.2.10 on 2024-03-11 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_card_limit_and_more'),
        ('card_manager', '0002_card_share_limit_card_third_party_share_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
