# Generated by Django 4.2.10 on 2024-03-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0003_alter_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
